service: sync-service

frameworkVersion: ">=1.2.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs8.10
  logs:
      restApi: true

custom:
  defaultStage: prod

functions:
  insertIntoJourneyTable :
            handler: handler.insertIntoJourneyTable
            events:
              - http:
                  method: post
                  path: insertintojourneytable

  insertIntoBusStopTable :
              handler: handler.insertIntoBusStopTable
              events:
                - http:
                    method: post
                    path: insertintobusstoptable

resources:
  Resources:

