service: sync-service


plugins:
  - serverless-webpack


provider:
  name: aws
  runtime: nodejs6.10

custom:
  webpackIncludeModules: true


functions:
  createJourneyTable :
      handler: handler.createJourneyTable
      events:
        - http:
            method: post
            path: createjourneytable

  createBusStopTable :
        handler: handler.createBusStopTable
        events:
          - http:
              method: post
              path: createbusstoptable

  dropJourneyTable :
            handler: handler.dropJourneyTable
            events:
              - http:
                  method: post
                  path: dropjourneytable

  dropBusStopTable :
          handler: handler.dropBusStopTable
          events:
            - http:
                method: post
                path: dropbusstoptable

  insertIntoJourneyTable :
            handler: handler.insertIntoJourneyTable
            events:
              - http:
                  method: post
                  path: insertintojourneytable

  insertIntoBusStopTable :
              handler: handler.insertIntoBusStopTable
              events:
                - http:
                    method: post
                    path: insertintobusstoptable

resources:
  Resources:

